"""empty message

Revision ID: 683b684fcdec
Revises: 980b752241aa
Create Date: 2026-04-27 10:53:06.556436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683b684fcdec'
down_revision = '980b752241aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('work', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('work')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
