"""empty message

Revision ID: 980b752241aa
Revises: e542caa6b95c
Create Date: 2026-04-27 10:42:35.689698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980b752241aa'
down_revision = 'e542caa6b95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('ai_language', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ai_language')
        batch_op.drop_column('ai_role')

    # ### end Alembic commands ###
